module.exports = {
  title: "vivace",
  description: "Hello :) Welcome to my blog!",
  author: "Vivace",
  siteUrl: "https://devhudi.github.io/gatsby-starter-hoodie/",
  links: {
//    github: "https://github.com/HS-711",
//    linkedIn: "https://linkedin.com",
//    facebook: "https://www.facebook.com",
//    twitter: "https://twitter.com",
//   x: "https://x.com",
//    instagram: "https://www.instagram.com/sl.7__7/",
//    medium: "https://medium.com",
    blogger: "https://blog.naver.com/billsmafia",
    email: "mailto:abcxyz02@g.skku.edu",
    resume: "https://vivace-hs.notion.site/Resume-45207bcbaff14d4d905241a5e4321225?pvs=74",
//    link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "devHudi/gatsby-starter-hoodie",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
